config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 500 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = Post.order(id: :asc)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: "投稿しました"
    else
      flash.now[:alert] = "投稿に失敗しました"
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "更新しました"
    else
      flash.now[:alert] = "更新に失敗しました"
      render :edit
    end
  end

  def destroy
    @post.destroy!
    redirect_to root_path, alert: "削除しました"
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_error_messages.html.erb
<% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger" role="alert">
      <a href="#" class="close" data-dismiss="alert">×</a>
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <div class="alert alert-<%= flash_type %>" role="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-primary fixed-top">
  <span class="navbar-brand">メッセージ投稿アプリ</span>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "投稿一覧", posts_path, class: "nav-item nav-link active" %>
      <%= link_to "新規投稿", new_post_path, class: "nav-item nav-link active" %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostBootstrapApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# レスポンシブ対応のためのviewport %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <main>
      <%= render "layouts/flash" %>
      <div class="base-container">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= render "layouts/error_messages" %>
<%= form_with model: @post, local: true do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_field :content, class: "form-control", rows: 10 %>
  </div>
  <div>
    <%= form.submit button_value, class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>編集</h1>
<%= render "form", button_value: "更新" %>

app/views/posts/index.html.erb
<h1 class="text-center">投稿一覧</h1>
<table class="table table-bordered table-striped mt-4">
  <thead class="table-primary">
    <tr>
      <th scope="col">No.</th>
      <th scope="col" class="w-100">タイトル</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each.with_index(1) do |post, i| %>
      <tr>
        <th scope="row" class="text-right"><%= i %></th>
        <td class="break-word"><%= post.title %></td>
        <td class="text-nowrap">
          <%= link_to post, class: "btn btn-primary" do %>
            <i class="fas fa-envelope-open-text"></i> <span class="d-none d-md-inline"> 詳細</span>
          <% end %>
          <%= link_to edit_post_path(post), class: "btn btn-success" do %>
            <i class="far fa-edit"></i> <span class="d-none d-md-inline"> 編集</span>
          <% end %>
          <%= link_to post, method: :delete, data: { confirm: "削除しますか?" }, class: "btn btn-danger" do %>
            <i class="far fa-trash-alt"></i> <span class="d-none d-md-inline"> 削除</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>新規投稿</h1>
<%= render "form", button_value: "投稿" %>

app/views/posts/show.html.erb
<h1 class="text-center">詳細表示</h1>
<section class="card border-dark mt-5">
  <div class="card-header">
    <h4><%= @post.title %></h4>
  </div>
  <div class="card-body">
    <p class="card-text"><%= simple_format(h @post.content) %></p>
  </div>
</section>